In [1]:
from absenteeism_module import *

model = absenteeism_model('model', 'scaler')

model.load_and_clean_data('Absenteeism_new_data.csv')

model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.692057,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.258066,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.411592,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.712007,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.737730,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.821531,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.382517,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.814923,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.310808,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.941359,1
13,0,0.0,0,1,6,179,30,19,1,0,0,0.462915,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.278840,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.200815,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.877630,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.859674,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.319652,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.879256,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
22,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.839584,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.661984,1
25,0,0.0,0,1,7,235,43,38,0,1,0,0.252104,0
26,0,0.0,1,0,7,233,31,21,1,1,8,0.950202,1
27,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.902845,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.322674,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.424076,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.273164,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.319911,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.536944,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.640912,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.823569,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.384864,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.127862,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.362675,0

In [8]:
import psycopg2

In [9]:
conn = psycopg2.connect("dbname=predicted_outputs user=paulo password =paulo")

In [10]:
cursor = conn.cursor()

In [12]:
cursor.execute("DROP TABLE predicted_outputs;")

cursor.execute("""CREATE TABLE predicted_outputs(
  reason_1 BOOLEAN NOT NULL,
  reason_2 BOOLEAN NOT NULL,
  reason_3 BOOLEAN NOT NULL,
  reason_4 BOOLEAN NOT NULL,
  month_value INT NOT NULL,
  transportation_expense INT NOT NULL,
  age INT NOT NULL,
  body_mass_index INT NOT NULL,
  education BOOLEAN NOT NULL,
  children INT NOT NULL,
  pets INT NOT NULL, 
  probability FLOAT NOT NULL,
  prediction BIT NOT NULL
);""")

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block